### ISSUE TITLE
\" in vocab files create error

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/JCdmBuilder#4]
In the latest vocab download the RXNorm extension contain Concept_names that have a ".....\\", e.g. concept_id 43684848 which is not accepted by JCdmBuilder.

After removal of these all works fine.

One could also argue that these should not have been generated in the first place by Athena?

**Comment by schuemie** [comment]
This problem was really in Usagi, and that should be fixed now. Also, the new Athena file reader should be more robust.
